---
receding_horizon: False
num_steps: 12
num_trials: 20
visualize: True
experiment_name: 'allegro_screwdriver'
mode: 'simulation'  # choose from 'simulation', 'hardware', 'hardware_copy'
# fingers: ['index', 'thumb']
fingers: ['index', 'middle', 'thumb']
object_type: 'screwdriver'
sim_device: 'cpu'
device: 'cuda:0'
friction_coefficient: 0.95
gradual_control: True
arm_type: 'None' # choose between 'None', 'robot', 'floating_3d', 'floating_6d'
gravity: True  # whether to use gravity in the simulation
goal: [0, 0, -1.5707]
kp: 3.0
controllers:
  mppi:
    T: 2
    N: 500
    # N: 200
    # lambda: 0.3
    lambda: 0.01
    variance: 0.005
    warmstart_iters: 5
    online_iters: 1
    include_velocity: True
