---
T: 11
receding_horizon: False
num_steps: 11
num_trials: 10
visualize: True
experiment_name: 'allegro_peg_insertion'
mode: 'simulation'  # choose from 'simulation', 'hardware', 'hardware_copy'
# fingers: ['index', 'thumb']
fingers: ['index', 'middle', 'thumb']
object_type: 'peg'
sim_device: 'cpu'
include_velocity: True
friction_coefficient: 0.95
kp: 3.0
controllers:
  mppi:
    # N: 16
    N: 100
    lambda: 1
    variance: 0.0001
    step_size: 0.1
    momentum: 0.
    # device: 'cuda:0'
    device: 'cpu'
