---
receding_horizon: False
num_steps: 10
num_trials: 30
visualize: True
experiment_name: 'allegro_peg_turning'
mode: 'simulation'  # choose from 'simulation', 'hardware', 'hardware_copy'
simulator: "isaac_gym" # choose from 'isaac_sim', 'isaac_gym'
fingers: ['index', 'middle', 'thumb']
object_type: 'short_peg'
sim_device: 'cpu'
device: 'cuda:0'
friction_coefficient: 0.95
kp: 6.0 # kp is increased to compenstate for gravity
visualize_plan: False
optimize_force: True
force_balance: False  # in addition to the torque balance, do we also need force balance, just for the screwdriver turning experiment w\o slot. 
gradual_control: True
arm_type: 'None' # choose between 'None', 'robot', 'floating_3d', 'floating_6d'
gravity: True  # whether to use gravity in the simulation
goal: [0, 0, 0, 0, -1.5707, 0]
controllers:
  mppi:
    T: 2
    N: 500
    lambda: 0.01
    variance: 0.005
    warmstart_iters: 5
    online_iters: 1
    include_velocity: True