---
receding_horizon: False
num_steps: 10
num_trials: 30
visualize: True
experiment_name: 'allegro_peg_alignment'
mode: 'simulation'  # choose from 'simulation', 'hardware', 'hardware_copy'
# fingers: ['index', 'thumb']
fingers: ['index', 'middle', 'thumb']
object_type: 'peg'
sim_device: 'cpu'
device: 'cuda:0'
friction_coefficient: 0.95
gradual_control: True
arm_type: 'None' # choose between 'None', 'robot', 'floating_3d', 'floating_6d'
gravity: True  # whether to use gravity in the simulation
goal: [-0.05, 0.0, 0.08, 0, 0, 0]
kp: 3.0
controllers:
  mppi:
    T: 2
    N: 500
    lambda: 0.01
    variance: 0.005
    warmstart_iters: 5
    online_iters: 1
    include_velocity: True

