---
T: 15
receding_horizon: False
num_steps: 15
num_trials: 20
num_turns: 4
visualize: True
experiment_name: 'tmp'
hardware: False
valve_type: 'cylinder'
sim_device: 'cuda:0'
friction_coefficient: 0.95
controllers:
  csvgd:
    # N: 16
    N: 16
    alpha_J: 5.0e-3
    alpha_C: 1.0
    step_size: 0.1
    momentum: 0.
    device: 'cuda:0'
    online_iters: 20
    warmup_iters: 100
    # warmup_iters: 10
    resample_steps: 1
    resample_sigma: 0.01
    resample_temperature: 1
    penalty: 10000
    collision_checking: False
    joint_friction: 0.0
    #model_path: 'data/training/allegro_valve/allegro_new_dataset_augment_angle_masked_2_diffusion/allegro_valve_diffusion.pt'
#  ipopt:
#    device: 'cpu'
#    online_iters: 10
#    warmup_iters: 100
#  mppi_1000:
#    N: 1000
#    lambda: 1.0e-4
#    sigma: 0.2
#    device: 'cuda:0'
#    penalty: 1000
#    online_iters: 25
#    warmup_iters: 250
##  svgd_1000:
##    M: 8
##    N: 128
##    step_size: 0.05
##    sigma: 0.25
##    lambda: 1.0e-4
##    use_grad: False
##    penalty: 1000
##    online_iters: 25
##    warmup_iters: 250
##    device: 'cuda:0'
#  mppi_100:
#    N: 1000
#    lambda: 1.0e-4
#    sigma: 0.2
#    device: 'cuda:0'
#    penalty: 100
#    online_iters: 25
#    warmup_iters: 250
#  svgd_100:
#    M: 8
#    N: 128
#    step_size: 0.1
#    sigma: 0.25
#    lambda: 1.0e-4
#    use_grad: False
#    penalty: 100
#    online_iters: 25
#    warmup_iters: 250
#    device: 'cuda:0'
#  svgd_grad_100:
#    M: 8
#    N: 128
#    step_size: 0.025
#    sigma: 0.25
#    lambda: 100
#    use_grad: True
#    penalty: 100
#    online_iters: 10
#    warmup_iters: 100
#    device: 'cuda:0'
#  svgd_grad_1000:
#    M: 8
#    N: 128
#    step_size: 0.025
#    sigma: 0.25
#    lambda: 100
#    use_grad: True
#    penalty: 1000
#    online_iters: 10
#    warmup_iters: 100
#    device: 'cuda:0'
