---
T: 10
receding_horizon: False
num_steps: 10
num_trials: 20
visualize: True
experiment_name: 'allegro_screwdriver'
mode: 'simulation'  # choose from 'simulation', 'hardware', 'hardware_copy'
simulator: "isaac_gym" # choose from 'isaac_sim', 'isaac_gym'
fingers: ['index', 'middle', 'thumb']
object_type: 'screwdriver'
sim_device: 'cpu'
device: 'cuda:1'
friction_coefficient: 0.95
kp: 3.0
visualize_plan: False
optimize_force: True
force_balance: False  # in addition to the torque balance, do we also need force balance, just for the screwdriver turning experiment w\o slot. 
gradual_control: True
arm_type: 'None' # choose between 'None', 'robot', 'floating_3d', 'floating_6d'
gravity: True  # whether to use gravity in the simulation
goal: [0, 0, -1.5707]
controllers:
  csvgd:
    N: 16
    # N: 4
    alpha_J: 5.0e-3
    # alpha_J: 1.0e-2
    alpha_C: 1
    step_size: 0.1
    momentum: 0.
    use_momentum: False
    online_iters: 50
    warmup_iters: 300
    resample_steps: 1
    resample_sigma: 0.01
    resample_temperature: 0.1
    penalty: 1000000
    collision_checking: False
    random_init_every_iter: False
    obj_gravity: True # whether to conside the object gravity in our optimization
    contact_region: True # whether to consider the contact region of the index finegr in our optimization
    static_init: False # whether to use the static initialization for the optimization
  ablation:
    N: 16
    alpha_J: 5.0e-3
    alpha_C: 1
    step_size: 0.1
    momentum: 0.
    online_iters: 50
    warmup_iters: 300
    resample_steps: 1
    resample_sigma: 0.01
    resample_temperature: 0.1
    penalty: 1000000
    collision_checking: False
    random_init_every_iter: False
    obj_gravity: True # whether to conside the object gravity in our optimization
  planning:
    N: 4  # for pregrasp
    solve_iters: 1000 
