---
T: 12
receding_horizon: False
num_steps: 11
num_trials: 1
visualize: True
experiment_name: 'allegro_screwdriver_6d'
mode: 'simulation'  # choose from 'simulation', 'hardware', 'hardware_copy'
# fingers: ['index', 'thumb']
fingers: ['index', 'middle', 'thumb']
object_type: 'screwdriver_6d'
sim_device: 'cuda:0'
friction_coefficient: 1.9
kp: 3.0
visualize_plan: False
optimize_force: True
exclude_index: False
controllers:
  csvgd:
    # N: 16
    N: 4
    alpha_J: 5.0e-3
    alpha_C: 1
    step_size: 0.1
    momentum: 0.
    device: 'cuda:0'
    online_iters: 100
    warmup_iters: 200
    resample_steps: 1
    resample_sigma: 0.01
    resample_temperature: 0.1
    penalty: 1000000
    collision_checking: False
    joint_friction: 0.0