---
T: 12
receding_horizon: False
num_steps: 11
num_trials: 10
visualize: True
experiment_name: 'allegro_screwdriver_collision_checking_small_force'
mode: 'simulation'  # choose from 'simulation', 'hardware', 'hardware_copy'
# fingers: ['index', 'thumb']
fingers: ['index', 'middle', 'thumb']
object_type: 'screwdriver'
sim_device: 'cuda:0'
friction_coefficient: 0.95
kp: 3.0
visualize_plan: True
optimize_force: True
exclude_index: False
force_balance: False  # in addition to the torque balance, do we also need force balance, just for the screwdriver turning experiment w\o slot. 
controllers:
  csvgd:
    # N: 16
    N: 4
    alpha_J: 5.0e-3
    # alpha_J: 1.0e-3 # DEBUG ONLY
    alpha_C: 1
    step_size: 0.1
    momentum: 0.
    device: 'cuda:0'
    online_iters: 50
    warmup_iters: 300
    resample_steps: 1
    resample_sigma: 0.01
    resample_temperature: 0.1
    penalty: 1000000
    collision_checking: True
    joint_friction: 0.0
    random_init_every_iter: False