---
T: 12
receding_horizon: False
num_steps: 12
num_turns: 3
num_trials: 10
visualize: True
experiment_name: 'allegro_screwdriver_constrained_rl_csvto_projection_warm_start_buffer'
# experiment_name: 'allegro_screwdriver_new_data_collection_5'
mode: 'simulation'  # choose from 'simulation', 'hardware', 'hardware_copy'
# fingers: ['index', 'thumb']
fingers: ['index', 'middle', 'thumb']
object_type: 'screwdriver'
sim_device: 'cpu'
friction_coefficient: 1.0
kp: 3.0
heuristic: 1000
max_depth: 11
goal: -1.5
prior: 1
multi_particle_search: True
replan: False
visualize_plan: True
optimize_force: True
exclude_index: False
projected: False
use_saved_plans: True
use_saved_noise: False
use_guidance: False
sample_contact: False
use_partial_constraint: True
sine_cosine: False
shortcut_trajectory: False
use_constraints: True
batch_size: 256

# RL Training Parameters
total_timesteps: 1000000
max_episode_steps: 20
eval_freq: 5000
checkpoint_freq: 10000
start_timesteps: 1000
buffer_size: 1000000
warm_start_buffer: True
lr_actor: .0003
lr_critic: .001
gamma: 0.99
tau: 0.005
policy_noise: 0.1
noise_clip: 0.5
policy_freq: 2
randomize_obj_start: False
randomize_rob_start: False
evaluate: True
eval_episodes: 10
render_eval: False
save_path: 'models/allegro_screwdriver_td3'

data_directory: 'allegro_screwdriver_data_gen_pi_2_close_contact'

# Prioritized Experience Replay
use_per: True
per_alpha: 0.6
per_beta: 0.4
per_beta_annealing: 0.0001

# Wandb Configuration
use_wandb: True
wandb_project: 'allegro-screwdriver-td3'
wandb_run_name: null  # Set to null for auto-generated names
wandb_tags: ['allegro', 'td3', 'constrained-rl', 'manipulation']
# model_path: 'data/training/allegro_screwdriver/allegro_better_model/allegro_screwdriver_diffusion_w_classifier.pt'
# model_path: 'data/training/allegro_screwdriver/allegro_test_new_data_augment_angle_diffusion/allegro_screwdriver_diffusion.pt'
device: 'cuda:1'
