---
T: 10
receding_horizon: False
num_steps: 10
num_trials: 20
visualize: True
experiment_name: 'allegro_peg_insertion_paper_computation_time'
mode: 'simulation'  # choose from 'simulation', 'hardware', 'hardware_copy'
# fingers: ['index', 'thumb']
fingers: ['index', 'middle', 'thumb']
object_type: 'peg'
sim_device: 'cpu'
friction_coefficient: 0.95
kp: 3.0
visualize_plan: False
optimize_force: True
use_arm: Falsecontrollers:
  csvgd:
    # N: 16
    N: 4
    alpha_J: 5.0e-3
    alpha_C: 1
    step_size: 0.1
    momentum: 0.
    device: 'cuda:0'
    online_iters: 40
    warmup_iters: 300
    resample_steps: 1
    resample_sigma: 0.01
    resample_temperature: 0.1
    penalty: 1000000
    collision_checking: False
    joint_friction: 0.0
    random_init_every_iter: False
    obj_gravity: True # whether to conside the obj gravity in our optimization
