---
T: 15
receding_horizon: False
num_steps: 15
num_turns: 3
num_trials: 10
visualize: False
experiment_name: 'allegro_screwdriver_diffusion_new_model_fixed_sequence_with_diff_high_budget'
# experiment_name: 'allegro_screwdriver_new_data_collection_5'
mode: 'simulation'  # choose from 'simulation', 'hardware', 'hardware_copy'
# fingers: ['index', 'thumb']
fingers: ['index', 'middle', 'thumb']
object_type: 'screwdriver'
sim_device: 'cpu'
friction_coefficient: 1.0
kp: 3.0
heuristic: 4000
max_depth: 11
goal: -1.5
prior: 1
sample_contact: False
multi_particle_search: True
visualize_plan: False
optimize_force: True
exclude_index: False
projected: False
use_saved_plans: True
use_saved_noise: False
use_guidance: False
use_partial_constraint: True
model_path: 'data/training/allegro_screwdriver/allegro_better_model/allegro_screwdriver_diffusion_w_classifier.pt'
# model_path: 'data/training/allegro_screwdriver/allegro_test_new_data_augment_angle_diffusion/allegro_screwdriver_diffusion.pt'
controllers:
  csvgd:
    # N: 16
    N: 16
    alpha_J: 5.0e-3
    alpha_C: 1
    step_size: 0.1
    momentum: 0.
    device: 'cuda:0'
    online_iters: 40
    warmup_iters: 250
    resample_steps: 16
    resample_sigma: 0.01
    resample_temperature: 0.1
    penalty: 1000000
    collision_checking: False
    joint_friction: 0.0
