---
T: 12
receding_horizon: False
num_steps: 11
num_trials: 5
visualize: True
experiment_name: 'allegro_valve'
mode: 'simulation'  # choose from 'simulation', 'hardware', 'hardware_copy'
fingers: ['index', 'middle', 'thumb']
simulator: "isaac_gym" # choose from 'isaac_sim', 'isaac_gym'
# fingers: ['index', 'middle', 'thumb', 'ring']
object_type: 'cross_valve'
# object_type: 'cylinder_valve'
sim_device: 'cuda:0'
device: 'cuda:0'
arm_type: "None"
friction_coefficient: 0.9
kp: 3.0
visualize_plan: True
random_robot_pose: False
optimize_force: True
gravity: True  # whether to use gravity in the simulation
goal: [-1.5707]
method: 'ablation'
controllers:
  csvgd:
    # N: 16
    N: 4
    alpha_J: 5.0e-3
    alpha_C: 1
    step_size: 0.1
    momentum: 0.
    online_iters: 30
    warmup_iters: 100
    resample_steps: 1
    resample_sigma: 0.01
    resample_temperature: 0.1
    penalty: 1000000
    collision_checking: False
    random_init_every_iter: False
  ablation:
    # N: 16
    N: 4
    alpha_J: 5.0e-3
    alpha_C: 1
    step_size: 0.1
    momentum: 0.
    online_iters: 30
    warmup_iters: 100
    resample_steps: 1
    resample_sigma: 0.01
    resample_temperature: 0.1
    penalty: 1000000
    collision_checking: False
    random_init_every_iter: False