---
T: 10
receding_horizon: False
num_steps: 10
num_trials: 20
visualize: True
experiment_name: 'allegro_peg_alignment'
mode: 'simulation'  # choose from 'simulation', 'hardware', 'hardware_copy'
simulator: "isaac_gym" # choose from 'isaac_sim', 'isaac_gym'
fingers: ['index', 'middle', 'thumb']
object_type: 'peg'
sim_device: 'cpu'
device: 'cuda:1'
friction_coefficient: 0.95
kp: 3.0
visualize_plan: True
optimize_force: True
gradual_control: True
use_arm: False
arm_type: 'None' # choose between 'None', 'robot', 'floating_3d', 'floating_6d'
gravity: True  # whether to use gravity in the simulation
goal: [0, 0, 0, 0, 0, 0]
method: 'ablation'
controllers:
  csvgd:
    # N: 16
    N: 4
    alpha_J: 5.0e-3
    alpha_C: 1
    step_size: 0.1
    momentum: 0.
    online_iters: 40
    warmup_iters: 300
    resample_steps: 1
    resample_sigma: 0.01
    resample_temperature: 0.1
    penalty: 1000000
    collision_checking: False
    random_init_every_iter: False
    obj_gravity: True # whether to conside the obj gravity in our optimization
  ablation:
    # N: 16
    N: 4
    alpha_J: 5.0e-3
    alpha_C: 1
    step_size: 0.1
    momentum: 0.
    online_iters: 40
    warmup_iters: 300
    resample_steps: 1
    resample_sigma: 0.01
    resample_temperature: 0.1
    penalty: 1000000
    collision_checking: False
    random_init_every_iter: False
    obj_gravity: True # whether to conside the obj gravity in our optimization