---
T: 4
T_orig: 12
receding_horizon: False
num_steps: 12
num_turns: 2
num_trials: 90
visualize: True
experiment_name: 'allegro_screwdriver_data_gen_pi_2'
# experiment_name: 'allegro_screwdriver_new_data_collection_5'
mode: 'simulation'  # choose from 'simulation', 'hardware', 'hardware_copy'
# fingers: ['index', 'thumb']
fingers: ['index', 'middle', 'thumb']
object_type: 'screwdriver'
sim_device: 'cpu'
friction_coefficient: 1.0
kp: 3.0
heuristic: 1000
max_depth: 11
goal: -1.5
prior: 1
multi_particle_search: True
replan: False
visualize_plan: False
visualize_recovery_plan: False
optimize_force: True
exclude_index: False
projected: False
use_saved_plans: True
use_saved_noise: False
use_guidance: False
sample_contact: False
use_partial_constraint: True
sine_cosine: False
shortcut_trajectory: False
randomize_obj_start: True
perturb_action: False
live_recovery: False
obj_gravity: False
start_ind: 270
# model_path: 'data/training/allegro_screwdriver/allegro_better_model/allegro_screwdriver_diffusion_w_classifier.pt'
# model_path: 'data/training/allegro_screwdriver/allegro_test_new_data_augment_angle_diffusion/allegro_screwdriver_diffusion.pt'
controllers:
  csvgd:
    # N: 16
    N: 16
    alpha_J: 1.0e-2
    alpha_C: 1
    step_size: 0.1
    momentum: 0.
    device: 'cuda:1'
    online_iters: 35
    warmup_iters: 150
    resample_steps: 16
    resample_sigma: 0.01
    resample_temperature: 0.1
    penalty: 1000000
    collision_checking: False
    joint_friction: 0.0