---
T: 15
receding_horizon: False
num_steps: 15
num_turns: 2
num_trials: 1
visualize: True
experiment_name: 'allegro_screwdriver_long_thumb_middle4'
mode: 'simulation'  # choose from 'simulation', 'hardware', 'hardware_copy'
# fingers: ['index', 'thumb']
fingers: ['index', 'middle', 'thumb']
object_type: 'screwdriver'
sim_device: 'cuda:0'
friction_coefficient: 1.0
kp: 3.0
visualize_plan: False
optimize_force: True
exclude_index: False
controllers:
  csvgd:
    # N: 16
    N: 8
    alpha_J: 1.0e-3
    alpha_C: 1
    step_size: 0.1
    momentum: 0.
    device: 'cuda:0'
    online_iters: 10
    warmup_iters: 50
    resample_steps: 16
    resample_sigma: 0.01
    resample_temperature: 0.1
    penalty: 1000000
    collision_checking: False
    joint_friction: 0.0