---
T: 10
receding_horizon: False
num_steps: 10
num_trials: 1
visualize: True
experiment_name: 'victor_wrench_real'
controllers:
  csvgd:
    N: 4
    alpha_J: 0.01
    alpha_C: 1
    step_size: 0.1
    momentum: .0
    device: 'cuda:0'
    online_iters: 10
    warmup_iters: 100
    resample_steps: 1
    resample_sigma: 0.01
    resample_temperature: 0.1
    penalty: 1000