---
model_name: 'quadrotor_multi_constraint'
load_model: 'none'
epochs: 100
batch_size: 512
lr: 1.0e-3
model_type: 'nf'
data_directory: 'quadrotor_multi_constraint'
device: 'cuda:0'
test_every: 10
normalize_data: False
# only applied to training with csvto gradient
use_csvto_gradient: False
num_samples: 16
optim_update_every: 16
# Only applies to using EMA for training
use_ema: False
ema_decay: 0.995
ema_warmup_steps: 1000
ema_update_every: 10