---
model_name: 'victor_table'
load_model: 'none'
epochs: 500
batch_size: 256
lr: 1.0e-4
model_type: 'cnf'
data_directory: 'victor_table'
device: 'cuda:0'
test_every: 1
normalize_data: True
# only applied to training with csvto gradient
use_csvto_gradient: False
num_samples: 16
optim_update_every: 16
# Only applies to using EMA for training
use_ema: True
ema_decay: 0.995
ema_warmup_steps: 1000
ema_update_every: 10