---
T: 12
receding_horizon: True
obstacle_mode: 'gp'
surface_constr: False
num_steps: 10
num_trials: 1000
visualize: False
experiment_name: 'quadrotor_flow_test_gp_sdf_1'
random_surface: True
controllers:
  csvgd:
    N: 16
    alpha_J: 1
    alpha_C: 1
    step_size: 1
    momentum: 0.
    device: 'cuda:0'
    online_iters: 20
    warmup_iters: 100
    resample_steps: 5
    resample_sigma: 0.1
    resample_temperature: 0.25
    penalty: 100.00
    flow_model: 'none'
#  csvgd_demonstration_flow:
#    N: 8
#    alpha_J: 1
#    alpha_C: 1
#    step_size: 0.5
#    momentum: 0.
#    device: 'cuda:0'
#    online_iters: 10
#    warmup_iters: 100
#    resample_steps: 5
#    resample_sigma: 0.1
#    resample_temperature: 0.25
#    penalty: 100.00
#    flow_model: 'spline_learned_sampler_quadrotor_multi_constraint_from_demonstration_controls_only2.pt'
#  csvgd_finetuned_flow:
#    N: 8
#    alpha_J: 1
#    alpha_C: 1
#    step_size: 0.5
#    momentum: 0.
#    device: 'cuda:0'
#    online_iters: 10
#    warmup_iters: 100
#    resample_steps: 5
#    resample_sigma: 0.1
#    resample_temperature: 0.25
#    penalty: 100.00
#    flow_model: 'spline_learned_sampler_quadrotor_multi_constraint_finetuned_controls_only2.pt'
#  ipopt:
#    device: 'cpu'
#    online_iters: 10
#    warmup_iters: 100
#  mppi_1000:
#    N: 1000
#    lambda: 1.0e-4
#    sigma: 0.25
#    device: 'cuda:0'
#    penalty: 1000
#    online_iters: 25
#    warmup_iters: 250
#  svgd_1000:
#    M: 8
#    N: 128
#    step_size: 0.1
#    sigma: 0.1
#    lambda: 1.0e-4
#    use_grad: False
#    penalty: 1000
#    online_iters: 25
#    warmup_iters: 250
#    device: 'cuda:0'
#  mppi_100:
#    N: 1000
#    lambda: 1.0e-4
#    sigma: 0.25
#    device: 'cuda:0'
#    penalty: 100
#    online_iters: 25
#    warmup_iters: 250
#  svgd_100:
#    M: 8
#    N: 128
#    step_size: 0.1
#    sigma: 0.1
#    lambda: 1.0e-4
#    use_grad: False
#    penalty: 100
#    online_iters: 25
#    warmup_iters: 250
#    device: 'cuda:0'
#  svgd_grad_1000:
#    M: 8
#    N: 128
#    step_size: 0.1
#    sigma: 0.1
#    lambda: 250
#    use_grad: True
#    penalty: 1000
#    online_iters: 25
#    warmup_iters: 250
#    device: 'cuda:0'
#  svgd_grad_100:
#    M: 8
#    N: 128
#    step_size: 0.1
#    sigma: 0.1
#    lambda: 250
#    use_grad: True
#    penalty: 100
#    online_iters: 25
#    warmup_iters: 250
#    device: 'cuda:0'