---
T: 12
receding_horizon: True
obstacle_mode: 'gp'
surface_constr: True
num_steps: 100
num_trials: 20
visualize: True
experiment_name: 'test_quadrotor_composable'
random_surface: True
controllers:
  csvgd:
    N: 16
    alpha_J: 0.1
    alpha_C: 1
    step_size: 0.5
    momentum: 0.
    device: 'cuda:0'
    online_iters: 10
    warmup_iters: 100
    resample_steps: 5
    resample_sigma: 0.1
    resample_temperature: 0.25
    penalty: 100.00
    flow_model: 'none'
  csvgd_diffusion_flow_surf_only:
    N: 16
    alpha_J: 0.1
    alpha_C: 1
    step_size: 0.5
    momentum: 0.
    device: 'cuda:0'
    online_iters: 10
    warmup_iters: 100
    resample_steps: 5
    resample_sigma: 0.1
    resample_temperature: 0.25
    penalty: 100.00
    flow_model: 'data/training/quadrotor/quadrotor_multi_constraint_surface_only_diffusion/from_demonstrations_ema.pt'
  csvgd_diffusion_flow_surf_and_obs:
    N: 16
    alpha_J: 0.1
    alpha_C: 1
    step_size: 0.5
    momentum: 0.
    device: 'cuda:0'
    online_iters: 100
    warmup_iters: 10
    resample_steps: 5
    resample_sigma: 0.1
    resample_temperature: 0.25
    penalty: 100.00
    flow_model: 'data/training/quadrotor/quadrotor_multi_constraint_obs_and_surf_diffusion/from_demonstrations_ema.pt'
#  csvgd_diffusion_flow_surf_only_no_opt:
#    N: 16
#    alpha_J: 1
#    alpha_C: 1
#    step_size: 1
#    momentum: 0.
#    device: 'cuda:0'
#    online_iters: 10
#    warmup_iters: 100
#    resample_steps: 5
#    resample_sigma: 0.1
#    resample_temperature: 0.25
#    penalty: 100.00
#    flow_model: 'data/training/quadrotor/quadrotor_multi_constraint_surface_only_diffusion/from_demonstrations_ema.pt'
#  csvgd_diffusion_flow_surf_and_obs_no_opt:
#    N: 16
#    alpha_J: 1
#    alpha_C: 1
#    step_size: 1
#    momentum: 0.
#    device: 'cuda:0'
#    online_iters: 0
#    warmup_iters: 0
#    resample_steps: 5
#    resample_sigma: 0.1
#    resample_temperature: 0.25
#    penalty: 100.00
#    flow_model: 'data/training/quadrotor/quadrotor_multi_constraint_obs_and_surf_diffusion/from_demonstrations_ema.pt'
#  ipopt:
#    device: 'cpu'
#    online_iters: 10
#    warmup_iters: 100
#  mppi_1000:
#    N: 1000
#    lambda: 1.0e-4
#    sigma: 0.25
#    device: 'cuda:0'
#    penalty: 1000
#    online_iters: 25
#    warmup_iters: 250
#  svgd_1000:
#    M: 8
#    N: 128
#    step_size: 0.1
#    sigma: 0.1
#    lambda: 1.0e-4
#    use_grad: False
#    penalty: 1000
#    online_iters: 25
#    warmup_iters: 250
#    device: 'cuda:0'
#  mppi_100:
#    N: 1000
#    lambda: 1.0e-4
#    sigma: 0.25
#    device: 'cuda:0'
#    penalty: 100
#    online_iters: 25
#    warmup_iters: 250
#  svgd_100:
#    M: 8
#    N: 128
#    step_size: 0.1
#    sigma: 0.1
#    lambda: 1.0e-4
#    use_grad: False
#    penalty: 100
#    online_iters: 25
#    warmup_iters: 250
#    device: 'cuda:0'
#  svgd_grad_1000:
#    M: 8
#    N: 128
#    step_size: 0.1
#    sigma: 0.1
#    lambda: 250
#    use_grad: True
#    penalty: 1000
#    online_iters: 25
#    warmup_iters: 250
#    device: 'cuda:0'
#  svgd_grad_100:
#    M: 8
#    N: 128
#    step_size: 0.1
#    sigma: 0.1
#    lambda: 250
#    use_grad: True
#    penalty: 100
#    online_iters: 25
#    warmup_iters: 250
#    device: 'cuda:0'