---
T: 12
receding_horizon: True
num_steps: 10
start_trial: 0
num_trials: 3500
visualize: False
simulate: False
experiment_name: 'victor_table_jointspace_train_new_8'
random_env: True
include_obstacles: False
include_table: True
obstacle_type: 'none'
table_height: 'random'
controllers:
  csvgd:
    N: 16
    alpha_J: 5.0e-3
    alpha_C: 1
    step_size: 0.25
    momentum: 0.
    device: 'cuda:0'
    online_iters: 10
    warmup_iters: 100
    resample_steps: 5
    resample_sigma: 0.01
    resample_temperature: 0.1
    penalty: 100
    flow_model: 'none'
#  csvgd_table_and_obstacle_diffusion:
#    N: 16
#    alpha_J: 5.0e-3
#    alpha_C: 1
#    step_size: 0.25
#    momentum: 0.
#    device: 'cuda:0'
#    online_iters: 10
#    warmup_iters: 100
#    resample_steps: 5
#    resample_sigma: 0.01
#    resample_temperature: 0.1
#    penalty: 100
#    flow_model: 'data/training/victor_table/victor_compose_2_diffusion/checkpoint.pth'
#  csvgd_table_diffusion:
#      N: 16
#      alpha_J: 5.0e-3
#      alpha_C: 1
#      step_size: 0.25
#      momentum: 0.
#      device: 'cuda:0'
#      online_iters: 10
#      warmup_iters: 100
#      resample_steps: 5
#      resample_sigma: 0.01
#      resample_temperature: 0.1
#      penalty: 100
#      flow_model: 'data/training/victor_table/victor_compose_2_diffusion/checkpoint.pth'
#  csvgd_obstacle_diffusion:
#      N: 16
#      alpha_J: 5.0e-3
#      alpha_C: 1
#      step_size: 0.25
#      momentum: 0.
#      device: 'cuda:0'
#      online_iters: 10
#      warmup_iters: 100
#      resample_steps: 5
#      resample_sigma: 0.01
#      resample_temperature: 0.1
#      penalty: 100
#      flow_model: 'data/training/victor_table/victor_compose_2_diffusion/checkpoint.pth'
#  csvgd_diffusion_obs_only:
#    N: 16
#    alpha_J: 5.0e-3
#    alpha_C: 1
#    step_size: 0.25
#    momentum: 0.
#    device: 'cuda:0'
#    online_iters: 10
#    warmup_iters: 100
#    resample_steps: 5
#    resample_sigma: 0.01
#    resample_temperature: 0.1
#    penalty: 100
#    flow_model: 'data/training/victor_table/victor_table_compose_diffusion/victor_table_diffusion.pt'
#  csvgd_diffusion_table_only:
#    N: 16
#    alpha_J: 5.0e-3
#    alpha_C: 1
#    step_size: 0.25
#    momentum: 0.
#    device: 'cuda:0'
#    online_iters: 10
#    warmup_iters: 100
#    resample_steps: 5
#    resample_sigma: 0.01
#    resample_temperature: 0.1
#    penalty: 100
#    flow_model: 'data/training/victor_table/victor_table_compose_diffusion/victor_table_diffusion.pt'
#  ipopt:
#    device: 'cpu'
#    online_iters: 10
#    warmup_iters: 100
#  mppi_1000:
#    N: 1000
#    lambda: 1.0e-4
#    sigma: 0.2
#    device: 'cuda:0'
#    penalty: 1000
#    online_iters: 25
#    warmup_iters: 250
##  svgd_1000:
##    M: 8
##    N: 128
##    step_size: 0.05
##    sigma: 0.25
##    lambda: 1.0e-4
##    use_grad: False
##    penalty: 1000
##    online_iters: 25
##    warmup_iters: 250
##    device: 'cuda:0'
#  mppi_100:
#    N: 1000
#    lambda: 1.0e-4
#    sigma: 0.2
#    device: 'cuda:0'
#    penalty: 100
#    online_iters: 25
#    warmup_iters: 250
#  svgd_100:
#    M: 8
#    N: 128
#    step_size: 0.1
#    sigma: 0.25
#    lambda: 1.0e-4
#    use_grad: False
#    penalty: 100
#    online_iters: 25
#    warmup_iters: 250
#    device: 'cuda:0'
#  svgd_grad_100:
#    M: 8
#    N: 128
#    step_size: 0.025
#    sigma: 0.25
#    lambda: 100
#    use_grad: True
#    penalty: 100
#    online_iters: 10
#    warmup_iters: 100
#    device: 'cuda:0'
#  svgd_grad_1000:
#    M: 8
#    N: 128
#    step_size: 0.025
#    sigma: 0.25
#    lambda: 100
#    use_grad: True
#    penalty: 1000
#    online_iters: 10
#    warmup_iters: 100
#    device: 'cuda:0'