---
model_name: 'allegro_screwdriver_recovery_best_traj_only_15000_training_weighted_random_downsample_balance_bugfix'
T: 9
dx: 15
du: 21
load_checkpoint: False
load_model: False
train_diffusion: True
train_classifier: False
eval_classifier: False
plot: False
vis_dataset: False
epochs: 15000
balance: 'weighted_random'
classifier_epochs: 100
batch_size: 256
lr: 1.0e-4
model_type: 'diffusion'
discriminator_guidance: True
inverse_dynamics: False
data_directory: 'allegro_screwdriver_recovery_data_bugfix'
device: 'cuda:0'
test_every: 9999999999
save_every: 500
normalize_data: True
constraint_embedding_dim: 64
constrained: False
guided: False
timesteps: 256
hidden_dim: 128
unconditional: True
sine_cosine: True
use_class: True
diffuse_class: False
# Only applies to using EMA for training
use_ema: True
ema_decay: 0.995
ema_warmup_steps: 1000
ema_update_every: 10
skip_pregrasp: True

test_directory: 'quadrotor_compose'
test_samples: False
test_name: None