---
model_name: 'allegro_test_new_new_data_dropout_v2_sin_cosine_valve'
T: 16
dx: 15
du: 21
load_checkpoint: False
load_model: False
train_diffusion: True
train_classifier: True
eval_classifier: False
plot: False
vis_dataset: False
epochs: 10000
classifier_epochs: 100
batch_size: 256
lr: 1.0e-4
model_type: 'diffusion'
discriminator_guidance: False
inverse_dynamics: True
data_directory: 'allegro_screwdriver_new_new'
device: 'cuda:1'
test_every: 10001
save_every: 10
normalize_data: True
constraint_embedding_dim: 64
constrained: False
guided: False
timesteps: 256
hidden_dim: 128
unconditional: True
sine_cosine: False
use_class: True
diffuse_class: False
# Only applies to using EMA for training
use_ema: True
ema_decay: 0.995
ema_warmup_steps: 1000
ema_update_every: 10

test_directory: 'quadrotor_compose'
test_samples: False
test_name: None