---
model_name: 'allegro_random_sdf_dataset_sine_cosine_256_timesteps_diffuse_class_model_long_train_batch_dropout_p_0.1'
T: 16
dx: 9
du: 8
load_checkpoint: False
epochs: 10000
batch_size: 128
lr: 1.0e-4
model_type: 'diffusion'
data_directory: 'test_collision_sdf'
device: 'cuda:0'
test_every: 500
save_every: 500
normalize_data: True
constraint_embedding_dim: 64
constrained: False
guided: False
timesteps: 256
hidden_dim: 128
unconditional: True
sine_cosine: True
use_class: True
diffuse_class: True
# Only applies to using EMA for training
use_ema: True
ema_decay: 0.995
ema_warmup_steps: 1000
ema_update_every: 10

test_directory: 'quadrotor_compose'
test_samples: False
test_name: None