model_name: 'allegro_cnf_state_control_only_turn_only_yaw_check_quintic_pred_noise'
T: 13
dx: 15
du: 21
skip_pregrasp: True
load_checkpoint: False
load_model: False
train_diffusion: True
train_classifier: False
eval_classifier: False
plot: False
vis_dataset: False
epochs: 10000
classifier_epochs: 100
batch_size: 256
lr: 1.0e-4
model_type: 'cnf'
discriminator_guidance: True
inverse_dynamics: False
data_directory: 'allegro_high_force_high_eps_pi_6'
device: 'cuda:0'
test_every: 10001
save_every: 10
normalize_data: True
constraint_embedding_dim: 64
constrained: False
guided: False
timesteps: 256
hidden_dim: 256
unconditional: True
sine_cosine: False
use_class: True
diffuse_class: False
# Only applies to using EMA for training
use_ema: True
ema_decay: 0.995
ema_warmup_steps: 1000
ema_update_every: 10
state_only: False
state_control_only: True
random_noise_dim: 1

test_directory: 'quadrotor_compose'
test_samples: False
test_name: None