---
T: 3
T_orig: 12
receding_horizon: False
num_turns: 1
max_recovery_stages: 4
num_episodes: 400
visualize: True
experiment_name: 'touchlegro_screwdriver_recovery_data'
mode: 'simulation'  # choose from 'simulation', 'hardware'
fingers: ['index', 'middle', 'thumb']
object_type: 'screwdriver'
sim_device: 'cpu'
kp: 3.0

# DIPS parameters. Not used in current method
heuristic: 1000
max_depth: 11
goal: -1.5

# Visualization parameters
visualize_plan: False # Visualize the task plan
visualize_recovery_plan: False # Visualize the recovery plan
visualize_contact_plan: True # Visualize the projected goal, plans for each contact mode in data generation

optimize_force: True # Use force in CSVTO. Should not change
sine_cosine: True # sine/cosine representation of screwdriver yaw
project_state: False
perturb_action: False # Add Gaussian noise to actions
randomize_obj_start: True # Randomize object start position. Should not change from True
external_wrench_perturb: True
random_force_magnitude: 1. # Maximum magnitude of the poking force
rand_pct: .33333 # Percentage of time to apply external wrench perturbation.
diff_init: True # Diffuse CSVTO initializations
live_recovery: True # Enable recovery during task execution
task_diffuse_goal: True # Override goal diffused from recovery model with task model goal projection
obj_gravity: True # Consider object gravity force n CSVTO force balance constraint

type: 'diffusion'
OOD_metric: 'likelihood'
recovery_controller: 'csvgd'
model_dir: 'data/training/allegro_screwdriver/touchlegro_screwdriver_task_model_diffusion'
model_path: 'data/training/allegro_screwdriver/touchlegro_screwdriver_task_model_diffusion/allegro_screwdriver_diffusion.pt'
likelihood_threshold: -100.0
likelihood_num_samples: 8 # Number of samples to use for likelihood computation. Lower is faster

controllers:
  csvgd:
    # N: 16
    N: 16
    alpha_J: 1.0e-2 # Cost learning rate for CSVTO
    alpha_C: 1 # Constraint learning rate for CSVTO
    step_size: 0.1
    momentum: 0.
    device: 'cuda:0'
    online_iters: 25 # Optimization budget for trajectory optimization. Lower is faster
    warmup_iters: 25 # Optimization budget for trajectory optimization. Lower is faster
    resample_steps: 16
    resample_sigma: 0.01
    resample_temperature: 0.1
    penalty: 1000000
    collision_checking: False
    joint_friction: 0.0