---
T: 3
T_orig: 12
receding_horizon: False
max_recovery_stages: 4
num_episodes: 50
visualize: True
experiment_name: 'touchlegro_screwdriver_hardware_eval'
mode: 'hardware'  # choose from 'simulation', 'hardware'
fingers: ['index', 'middle', 'thumb']
object_type: 'screwdriver'
sim_device: 'cpu'
friction_coefficient: 1.0
kp: 3.0

# DIPS parameters. Not used in current method
heuristic: 1000 # Constraint learning rate for CSVTO
max_depth: 11
goal: -.5
prior: 1

# Visualization parameters
visualize_plan: False # Visualize the task plan
visualize_recovery_plan: True # Visualize the recovery plan
visualize_contact_plan: True # Visualize the projected goal, plans for each contact mode in recovery data generation
visualize_recovery_planning_samples: False # Visualize the planning samples for each contact mode in recovery data generation

optimize_force: True # Use force in CSVTO. Should not change from True
sine_cosine: True # sine/cosine representation of screwdriver yaw. Should not change from True
perturb_action: False # Add Gaussian noise to actions. Should not change from False
diff_init: True # Diffuse CSVTO initializations. Should not change from True
generate_context: True # Diffuse contact mode for recovery model. Should not change from True
live_recovery: True # Enable recovery during task execution. Should not change from True
task_diffuse_goal: False # Override goal diffused from recovery model with task model goal projection
obj_gravity: True # Consider object gravity force n CSVTO force balance constraint

recovery_model_dir: 'data/training/allegro_screwdriver/touchlegro_screwdriver_recovery_diffusion'
model_path: 'data/training/allegro_screwdriver/touchlegro_screwdriver_recovery_diffusion/allegro_screwdriver_diffusion.pt'
model_dir: 'data/training/allegro_screwdriver/touchlegro_screwdriver_task_model_diffusion'
task_model_path: 'data/training/allegro_screwdriver/touchlegro_screwdriver_task_model_diffusion/allegro_screwdriver_diffusion.pt'
type: 'diffusion'
OOD_metric: 'likelihood'
recovery_controller: 'csvgd'
likelihood_threshold: -100
likelihood_num_samples: 8 # Number of samples to use for likelihood computation. Lower is faster

N_contact_plan: 64 # Number of joint (contact mode, trajectory) samples to generate before recovery. Higher is better, but slower and uses more GPU
controllers:
  csvgd:
    N: 16 
    alpha_J: 1.0e-2 # Cost learning rate for CSVTO (Constrained Stein Variational Trajectory Optimization)
    alpha_C: 1 # Constraint learning rate for CSVTO
    step_size: 0.1
    momentum: 0.
    device: 'cuda:0'
    online_iters: 25 # Optimization budget for trajectory optimization. Lower is faster
    warmup_iters: 25 # Optimization budget for trajectory optimization. Lower is faster
    resample_steps: 16
    resample_sigma: 0.01
    resample_temperature: 0.1
    penalty: 1000000
    collision_checking: False
    joint_friction: 0.0