---
T: 15
receding_horizon: True
num_steps: 10
num_trials: 20
visualize: True
simulate: True
experiment_name: 'kuka_test'
start_trial: 0
controllers:
  csvgd:
    N: 8
    alpha_J: 1.0
    alpha_C: 1.0
    step_size: 0.1
    momentum: 0.
    device: 'cuda:0'
    online_iters: 10
    warmup_iters: 10
    resample_steps: 100
    resample_sigma: 0.01
    resample_temperature: 0.5
    penalty: 1000
