---
T: 10
receding_horizon: False
num_steps: 10
num_trials: 1
visualize: False
experiment_name: 'victor_wrench_timing'
controllers:
  csvgd:
    N: 4
    alpha_J: 0.01
    alpha_C: 1
    step_size: 0.1
    momentum: .0
    device: 'cuda:0'
    online_iters: 10
    warmup_iters: 100
    resample_steps: 1
    resample_sigma: 0.01
    resample_temperature: 0.1
    penalty: 1000
  ipopt:
    device: 'cpu'
    online_iters: 10
    warmup_iters: 100
  mppi_1000:
    N: 1000
    lambda: 1.0e-4
    sigma: 0.25
    device: 'cuda:0'
    penalty: 1000
    online_iters: 25
    warmup_iters: 250
  svgd_1000:
    M: 4
    N: 128
    step_size: 0.1
    sigma: 0.5
    lambda: 1.0e-4
    use_grad: False
    penalty: 1000
    online_iters: 25
    warmup_iters: 250
    device: 'cuda:0'
  mppi_100:
    N: 100
    lambda: 1.0e-4
    sigma: 0.25
    device: 'cuda:0'
    penalty: 100
    online_iters: 25
    warmup_iters: 250
  svgd_100:
    M: 4
    N: 128
    step_size: 0.1
    sigma: 0.5
    lambda: 1.0e-4
    use_grad: False
    penalty: 100
    online_iters: 50
    warmup_iters: 500
    device: 'cuda:0'
  svgd_grad_100:
    M: 4
    N: 128
    step_size: 0.1
    sigma: 0.05
    lambda: 500
    use_grad: True
    penalty: 100
    online_iters: 10
    warmup_iters: 100
    device: 'cuda:0'
  svgd_grad_1000:
    M: 4
    N: 128
    step_size: 0.1
    sigma: 0.05
    lambda: 500
    use_grad: True
    penalty: 1000
    online_iters: 10
    warmup_iters: 100
    device: 'cuda:0'