python train_allegro_screwdriver.py --config allegro_screwdriver_diffusion_5_10_15_7000_training_no_downsample_best_traj_only.yaml
python train_allegro_screwdriver.py --config allegro_screwdriver_diffusion_5_10_15_7000_training_no_downsample_best_traj_only_.5_dropout.yaml
python train_allegro_screwdriver.py --config allegro_screwdriver_diffusion_5_10_15_7000_training_no_downsample_all_particles_.5_dropout.yaml
