---
T: 8
receding_horizon: False
num_steps: 8
num_turns: 5
num_trials: 10
visualize: True
experiment_name: 'allegro_card_csvto_diff_plan_max_likelihood_128'
# experiment_name: 'allegro_screwdriver_new_data_collection_5'
mode: 'simulation'  # choose from 'simulation', 'hardware', 'hardware_copy'
fingers: ['index', 'middle']
sim_device: 'cpu'
friction_coefficient: 1.0
kp: 10.0
heuristic: 100000
max_depth: 11
prior: 1
goal: -.02
goal_update: -.02
num_samples: 128
multi_particle_search: False
replan: True
visualize_plan: False
optimize_force: True
projected: False
use_saved_plans: True
use_saved_noise: False
use_guidance: False
sample_contact: True
use_partial_constraint: False
sine_cosine: True
data_gen: False
model_path: 'data/training/allegro_card/allegro_card_diffusion/allegro_screwdriver_diffusion_w_classifier.pt'
controllers:
  csvgd:
    # N: 16
    N: 16
    alpha_J: 1.0e-2
    alpha_C: 1
    step_size: 0.1
    momentum: 0.
    device: 'cuda:0'
    online_iters: 35
    warmup_iters: 150
    resample_steps: 16
    resample_sigma: 0.01
    resample_temperature: 0.1
    penalty: 1000000
    collision_checking: False
    joint_friction: 0.0