---
T: 3
T_orig: 12
receding_horizon: False
num_steps: 8
num_turns: 1
max_recovery_stages: 4
num_trials: 10
num_episodes: 200
visualize: True
experiment_name: 'allegro_screwdriver_recovery_data_pi_6_rand_pct_.25_2_N_r_.5_1'
mode: 'simulation'  # choose from 'simulation', 'hardware', 'hardware_copy'
# fingers: ['index', 'thumb']
fingers: ['index', 'middle', 'thumb']
object_type: 'screwdriver'
sim_device: 'cpu'
friction_coefficient: 1.0
kp: 3.0
heuristic: 1000
max_depth: 11
goal: -1.5
prior: 1
multi_particle_search: True
replan: False
visualize_plan: False
visualize_recovery_plan: False
visualize_contact_plan: True
optimize_force: True
exclude_index: False
projected: False
use_saved_plans: True
use_saved_noise: False
use_guidance: False
sample_contact: False
use_partial_constraint: True
sine_cosine: True
project_state: False
compute_recovery_trajectory: False
rl_adjustment: False
test_recovery_trajectory: False
perturb_action: False
randomize_obj_start: True
external_wrench_perturb: True
viz_states: False
diff_init: True
live_recovery: True
new_projection: True
task_diffuse_goal: True
obj_gravity: True
type: 'diffusion'
model_path: 'data/training/allegro_screwdriver/allegro_high_force_high_eps_pi_6_diffusion/allegro_screwdriver_diffusion_w_classifier.pt'
model_dir: 'data/training/allegro_screwdriver/allegro_high_force_high_eps_pi_6_diffusion'
likelihood_threshold: -160.0
drop_threshold: -1250
project_threshold: -105.
sac_batch_size: 64
# likelihood_threshold: -16.0
# likelihood_threshold: -136.6758056640625
# project_threshold: -90
# parity: 654
start_ind: 600
end_ind: 800
controllers:
  csvgd:
    # N: 16
    N: 16
    alpha_J: 1.0e-2
    alpha_C: 1
    step_size: 0.1
    momentum: 0.
    device: 'cuda:1'
    online_iters: 25
    warmup_iters: 50
    resample_steps: 16
    resample_sigma: 0.01
    resample_temperature: 0.1
    penalty: 1000000
    collision_checking: False
    joint_friction: 0.0