---
T: 3
T_orig: 12
receding_horizon: False
num_turns: 1
max_recovery_stages: 4
num_episodes: 50
visualize: True
experiment_name: 'touchlegro_screwdriver_recovery_model'
mode: 'simulation'  # choose from 'simulation', 'hardware', 'hardware_copy'
# fingers: ['index', 'thumb']
fingers: ['index', 'middle', 'thumb']
object_type: 'screwdriver'
sim_device: 'cpu'
kp: 3.0
heuristic: 1000
max_depth: 11
goal: -.5
visualize_plan: False
visualize_recovery_plan: True
visualize_contact_plan: True
optimize_force: True
use_guidance: False
sample_contact: False
sine_cosine: True
project_state: False
perturb_action: False
randomize_obj_start: True
external_wrench_perturb: False
diff_init: True
live_recovery: True
new_projection: True
trajectory_condition: True
generate_context: True
task_diffuse_goal: False
recovery_diff_traj: True
obj_gravity: True
type: 'diffusion'
OOD_metric: 'likelihood'
recovery_controller: 'csvgd'
recovery_model_dir: 'data/training/allegro_screwdriver/touchlegro_screwdriver_recovery_pi_2_25_downweight_diffusion'
model_path: 'data/training/allegro_screwdriver/touchlegro_screwdriver_recovery_pi_2_25_downweight_diffusion/allegro_screwdriver_diffusion.pt'
model_dir: 'data/training/allegro_screwdriver/touchlegro_screwdriver_pi_2_best_traj_only_diffusion'
model_path_orig: 'data/training/allegro_screwdriver/touchlegro_screwdriver_pi_2_best_traj_only_diffusion/allegro_screwdriver_diffusion.pt'
likelihood_threshold: -120.0
start_ind: 0
end_ind: 50
N_contact_plan: 32
likelihood_num_samples: 4
controllers:
  csvgd:
    N: 16
    alpha_J: 1.0e-2
    alpha_C: 1
    step_size: 0.1
    momentum: 0.
    device: 'cuda:0'
    online_iters: 25
    warmup_iters: 25
    resample_steps: 16
    resample_sigma: 0.01
    resample_temperature: 0.1
    penalty: 1000000
    collision_checking: False
    joint_friction: 0.0