_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.8.0
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.8.0
            "5": 0.18.3
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
batch_size:
    value: 64
epochs:
    value: 1000
learning_rate:
    value: 0.0001
