T: 12
receding_horizon: True
obstacle_mode: 'none'
num_steps: 100
num_trials: 1
experiment_name: 'quadrotor_no_obs_test'
include_x0: True
N: 8
alpha_J: 0.1
alpha_C: 1
step_size: 0.5
momentum: 0.0
device: 'cuda:0'
iters: 1
resample_steps: 10
resample_sigma: 0.1
resample_temperature: 0.5
penalty: 1000
squared_slack: True
use_true_hess: False
